# Generated by Django 5.0.2 on 2024-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.CharField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
