# Generated by Django 5.0.2 on 2024-03-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm1', '0004_savedschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedschedule',
            old_name='dept',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='savedschedule',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
